version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@parcel/packager-raw-url"
    versions:
    - 2.0.0-nightly.2247
    - 2.0.0-nightly.2250
    - 2.0.0-nightly.2251
    - 2.0.0-nightly.2252
    - 2.0.0-nightly.2254
    - 2.0.0-nightly.2255
    - 2.0.0-nightly.2256
    - 2.0.0-nightly.2258
    - 2.0.0-nightly.2259
    - 2.0.0-nightly.2260
    - 2.0.0-nightly.2261
    - 2.0.0-nightly.2263
    - 2.0.0-nightly.2264
    - 2.0.0-nightly.2265
    - 2.0.0-nightly.2267
    - 2.0.0-nightly.2268
    - 2.0.0-nightly.2270
  - dependency-name: "@parcel/transformer-stylus"
    versions:
    - 2.0.0-nightly.625
    - 2.0.0-nightly.628
    - 2.0.0-nightly.629
    - 2.0.0-nightly.630
    - 2.0.0-nightly.632
    - 2.0.0-nightly.633
    - 2.0.0-nightly.634
    - 2.0.0-nightly.636
    - 2.0.0-nightly.637
    - 2.0.0-nightly.638
    - 2.0.0-nightly.639
    - 2.0.0-nightly.641
    - 2.0.0-nightly.642
    - 2.0.0-nightly.643
    - 2.0.0-nightly.645
    - 2.0.0-nightly.646
    - 2.0.0-nightly.648
  - dependency-name: "@parcel/transformer-pug"
    versions:
    - 2.0.0-nightly.625
    - 2.0.0-nightly.628
    - 2.0.0-nightly.630
    - 2.0.0-nightly.632
    - 2.0.0-nightly.633
    - 2.0.0-nightly.634
    - 2.0.0-nightly.636
    - 2.0.0-nightly.637
    - 2.0.0-nightly.638
    - 2.0.0-nightly.639
    - 2.0.0-nightly.641
    - 2.0.0-nightly.642
    - 2.0.0-nightly.643
    - 2.0.0-nightly.645
    - 2.0.0-nightly.646
    - 2.0.0-nightly.648
  - dependency-name: "@parcel/transformer-webmanifest"
    versions:
    - 2.0.0-nightly.2244
    - 2.0.0-nightly.2247
    - 2.0.0-nightly.2250
    - 2.0.0-nightly.2251
    - 2.0.0-nightly.2252
    - 2.0.0-nightly.2254
    - 2.0.0-nightly.2255
    - 2.0.0-nightly.2256
    - 2.0.0-nightly.2258
    - 2.0.0-nightly.2259
    - 2.0.0-nightly.2260
    - 2.0.0-nightly.2261
    - 2.0.0-nightly.2263
    - 2.0.0-nightly.2264
    - 2.0.0-nightly.2265
    - 2.0.0-nightly.2267
    - 2.0.0-nightly.2268
    - 2.0.0-nightly.2270
  - dependency-name: parcel
    versions:
    - 2.0.0-nightly.623
    - 2.0.0-nightly.626
    - 2.0.0-nightly.627
    - 2.0.0-nightly.628
    - 2.0.0-nightly.630
    - 2.0.0-nightly.631
    - 2.0.0-nightly.632
    - 2.0.0-nightly.634
    - 2.0.0-nightly.635
    - 2.0.0-nightly.636
    - 2.0.0-nightly.637
    - 2.0.0-nightly.639
    - 2.0.0-nightly.640
    - 2.0.0-nightly.641
    - 2.0.0-nightly.643
    - 2.0.0-nightly.644
    - 2.0.0-nightly.646
  - dependency-name: parcel-reporter-static-files-copy
    versions:
    - 1.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: pug
    versions:
    - 3.0.2
