name: Build AdhdSenpai.com

on: 
  push:
    branches:
      - master

jobs:
  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm Install

    - name: Build adhdsenpai.com
      run: |
        rm -rf dist
        npm run build-adhd
    - name: Upload adhdsenpai.com
      run: |
        cd dist
        npx wrangler publish -c .\cfg\adhdsenpai.toml --outdir dist
        cd .. 
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
