name: Build Oddball.tf

on: 
  push:
    branches:
      - master

jobs:
  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm Install
      run: npm install
    - name: Run Gulp
      run: gulp
      
    - uses: docker://google/cloud-sdk
    - name: Set up Google Cloud
      run: |
        echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        
    - name: Upload compiled site to GCS
      run: |
        cd out
        gsutil -m cp -r ./ gs://oddball.tf
